name: LankaTransit  
description: "A new Flutter project."

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.2.0 

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.1.0
  shared_preferences: ^2.2.2
  qr_flutter: ^4.1.0
<<<<<<< Updated upstream
  image_picker: ^1.0.4
  geolocator: ^10.1.0
  mobile_scanner: ^3.4.1
=======
  image_picker: ^1.2.1
  geolocator: ^11.0.1  
  mobile_scanner: ^7.2.0
>>>>>>> Stashed changes
  google_maps_flutter: ^2.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.6

flutter:
  uses-material-design: true
  assets:
    - assets/bus_icon.png

flutter_launcher_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/bus.png"
  min_sdk_android: 21 

flutter_native_splash:
  color: "#ffffff"
  image: "assets/bus.png"
  android_12:
    image: "assets/bus.png"
  ios: true